services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: taskmanager_app
    restart: always
    volumes:
      - ./src:/app
    command: >
      sh -c "
      alembic -c alembic.ini upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: taskmanager_db
    restart: always
    ports:
      - "${HOST_PORT_DB}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmanager_pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
